### ISSUE TITLE
关于编码器

### ISSUE THREAD

**Issue by senzi96** [Nana0Nana/N.A.G.E.K.I.#1]
想请问下大佬用什么输出方式和脉冲的编码器比较好呢

**Comment by Nana0Nana** [comment]
集电极开路，100-400p以内

**Comment by senzi96** [comment]
> 集电极开路，100-400p以内

还有想请问一下，刚刚用100p的编码器更新到2.0固件出现了游戏和系统中位置抖动的问题，1.0固件的时候没有这个问题，请问是编码器脉冲较低么还可能是什么情况导致的。

**Comment by Nana0Nana** [comment]
> > 集电极开路，100-400p以内
> 
> 还有想请问一下，刚刚用100p的编码器更新到2.0固件出现了游戏和系统中位置抖动的问题，1.0固件的时候没有这个问题，请问是编码器脉冲较低么还可能是什么情况导致的。

如果用的是电位器，请把编码器部分代码删除，如果是编码器请把电位器部分代码删除，并且编码器屏蔽线与GND相连

**Comment by Nana0Nana** [comment]
> > 集电极开路，100-400p以内
> 
> 还有想请问一下，刚刚用100p的编码器更新到2.0固件出现了游戏和系统中位置抖动的问题，1.0固件的时候没有这个问题，请问是编码器脉冲较低么还可能是什么情况导致的。

如果是旋转编码器就删除lever部分代码，或者直接从loop中删除lever函数，如果是电位器就删除encoder

**Comment by senzi96** [comment]
> > > 集电极开路，100-400p以内
> > 
> > 
> > 还有想请问一下，刚刚用100p的编码器更新到2.0固件出现了游戏和系统中位置抖动的问题，1.0固件的时候没有这个问题，请问是编码器脉冲较低么还可能是什么情况导致的。
> 
> 如果是旋转编码器就删除lever部分代码，或者直接从loop中删除lever函数，如果是电位器就删除encoder

谢谢您！问题解决了。还有就是请问您觉得旋转编码器和电位器比哪个玩起来更好延迟更低呢？

**Comment by Nana0Nana** [comment]
> > > > 集电极开路，100-400p以内
> > > 
> > > 
> > > 还有想请问一下，刚刚用100p的编码器更新到2.0固件出现了游戏和系统中位置抖动的问题，1.0固件的时候没有这个问题，请问是编码器脉冲较低么还可能是什么情况导致的。
> > 
> > 
> > 如果是旋转编码器就删除lever部分代码，或者直接从loop中删除lever函数，如果是电位器就删除encoder
> 
> 谢谢您！问题解决了。还有就是请问您觉得旋转编码器和电位器比哪个玩起来更好延迟更低呢？

延迟理论上来说电位器会更低，但体验不出来，电位器数值更加精准，编码器方便固定

**Comment by senzi96** [comment]
谢谢您！完美地解决了我的问题！
